name: 'Setup Terraform and Terragrunt'
description: 'Setup Terraform and Terragrunt'

runs:
  using: 'composite'
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest
        terraform_wrapper: false

    - name: Install Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
      shell: bash
