---
- name: Configure Host
  gather_facts: true
  hosts: all
  tasks:
    - name: Configure Docker
      ansible.builtin.include_role:
        name: docker_host
    - name: Configure Users
      ansible.builtin.include_role:
        name: user_management
